# common containers shared across all pega instances
# run $ docker-compose run pdm-install in order to install Pega Deployment Manager before everything else

version: '3.1'
services:
  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1001               #change PUID if needed
      - PGID=1002               #change PGID if needed
      - TZ=Europe/Berlin        #change Time Zone if needed
      - URL=pega.example.com    #insert your domain name - yourdomain.url
      - VALIDATION=http
      - EMAIL=pega@example.com  #email for notifications
      - SUBDOMAINS=pega870-web,pega870-cdh,constellation870,pdm
    volumes:
      - ./appdata/swag:/config
    networks:
      - pega_common
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  adminer:
    image: adminer
    networks:
      - pega_common
    restart: unless-stopped

  constellation870:
    image: ${CONSTELLATION_RUN_IMAGE}
    volumes:
      - ./ssl-cert:/host_folder
    networks:
      - pega_common
    command: debug

  pdm-db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD
    networks:
      - pega_common
    restart: unless-stopped

  pdm-install:
    image: ${PEGA_INSTALL_IMAGE}
    profiles:
      - pdm_install
    depends_on:
      - "pdm-db"
    environment:
      - ACTION=install
      - SYSTEM_NAME=pdm
      - PRODUCTION_LEVEL=2
      - BYPASS_UDF_GENERATION=true
      - JDBC_URL=jdbc:postgresql://pdm-db:5432/postgres
      - JDBC_DRIVER_URI
      - DB_TYPE
      - JDBC_CLASS
      - DB_USERNAME
      - DB_PASSWORD
      - RULES_SCHEMA
      - DATA_SCHEMA
      - CUSTOMERDATA_SCHEMA
      - ADMIN_PASSWORD
    networks:
      - pega_common

  pdm:
    image: ${PEGA_RUN_IMAGE}
    container_name: pdm
    depends_on:
      - "pdm-db"
    environment:
      - NODE_TYPE=BackgroundProcessing,WebUser,Search,Stream
      - NODE_TIER=web
      - JDBC_URL=jdbc:postgresql://pdm-db:5432/postgres
      - JDBC_DRIVER_URI
      - DB_TYPE
      - JDBC_CLASS
      - DB_USERNAME
      - DB_PASSWORD
      - RULES_SCHEMA
      - DATA_SCHEMA
      - CUSTOMERDATA_SCHEMA
      - ADMIN_PASSWORD
    networks:
      - pega_common

networks:
  pega_common:
    name: pega_common
